title: Bisq
url: "https://bisq.network"
markdown: kramdown
permalink: /blog/:title/
livereload: true
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
feed:
  path: blog/feed.atom
include:
  - _redirects
exclude:
  - CNAME
  - README
  - Gemfile
paginate: 10
paginate_path: "/blog/page/:num/"
client_version: "0.9.4"
description: "Bisq is an open-source desktop application that allows you to buy and sell bitcoins in exchange for national currencies, or alternative crypto currencies."
